version: 2

sources:
  - name: staging
    schema: staging

    tables:
      - name: patients
      - name: appointments
      - name: billing
      - name: doctors
      - name: hospitals
      - name: treatments